[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/landing"
  to = "/landing/index.html"
  status = 200

[[redirects]]
  from = "/landing/*"
  to = "/landing/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


